
model_type: resnet50
pretrained: true
dropout: 0.5


data_dir: ./data/raw
csv_file: ocisceni_podaci.csv
output_dir: ./results/models


img_size: 224
batch_size: 32
num_workers: 4


epochs: 25
learning_rate: 0.0001
weight_decay: 0.0001


scheduler: cosine
lr_factor: 0.5
lr_patience: 3
min_lr: 0.00001


loss_type: focal
use_class_weights: true
focal_gamma: 2.0

# Early stopping
patience: 7
monitor_metric: balanced_acc

use_cuda: true
grad_clip_value: 1.0

k_folds: 5
create_ensemble: true


use_mixed_precision: true
pin_memory: true


ensemble_method: average

