model:
  architectures:
    - resnet50
    - efficientnet_b0
    - convnext_tiny
    - mobilenetv3_large
  pretrained: true
  dropout: 0.5
  img_size: 256

data:
  data_dir: ./data/train
  csv_file: balanced_data.csv
  output_dir: ./models/
  valid_size: 0.2

training:
  batch_size: 32
  num_workers: 4
  epochs: 25
  learning_rate: 0.0002
  weight_decay: 0.0001
  scheduler: cosine
  lr_factor: 0.5
  lr_patience: 3
  min_lr: 0.00001
  early_stopping_patience: 7
  monitor_metric: balanced_acc
  use_class_weights: true
  use_mixed_precision: true
  pin_memory: true
  grad_clip_value: 1.0

kfold:
  use_kfold: true
  n_splits: 5
  shuffle: true
  random_state: 42

ensemble:
  create_ensemble: true
  method: average
  optimize_threshold: true
  target_recall: 0.9
  min_precision: 0.7

fairness:
  evaluate_by_group: true
  balance_groups: false