model_type: resnet50
pretrained: true
dropout: 0.5


data_dir: C:\Users\Marko\MELANOMA\ISIC_2020_Training_JPEG\train
csv_file: balansirani_podaci_1.csv
output_dir: ./results/models


img_size: 224
batch_size: 32
num_workers: 4


epochs: 30
learning_rate: 0.0001
weight_decay: 0.0001


scheduler: cosine
lr_factor: 0.5
lr_patience: 3
min_lr: 0.00001


loss_type: cross_entropy
use_class_weights: true
focal_gamma: 2.0


patience: 7
monitor_metric: loss


use_cuda: true
grad_clip_value: 1.0