# Model parametri
model_type: resnet50  # resnet18, resnet34, resnet50, resnet101, resnet152, vanilla_resnet50, densenet121
pretrained: true      # Da li koristiti pretreniran model
dropout: 0.5          # Stopa dropout-a za regularizaciju

# Direktorijumi
data_dir: ./data/raw           # Folder sa trening i validacionim podacima
csv_file: ocisceni_podaci.csv  # CSV fajl za trening i validaciju
test_dir: ./data/test          # Odvojeni folder samo za test podatke
test_csv_file: test_podaci.csv # CSV fajl za test podatke
val_size: 0.2                  # Procenat podataka za validacij

# Veličina i parametri učitavanja podataka
img_size: 224
batch_size: 32
num_workers: 4

# Trening parametri
epochs: 30
learning_rate: 0.0001
weight_decay: 0.0001

# Learning rate scheduler
scheduler: cosine     # plateau, cosine, ili null
lr_factor: 0.5        # Samo za plateau scheduler
lr_patience: 3        # Samo za plateau scheduler
min_lr: 0.00001       # Minimalna vrednost lr-a

# Loss funkcija i balansiranje
loss_type: cross_entropy  # cross_entropy ili focal
use_class_weights: true   # Da li koristiti class weights za loss funkciju
focal_gamma: 2.0          # Samo za focal loss

# Early stopping
patience: 7              # Broj epoha bez poboljšanja za early stopping
monitor_metric: loss     # Metrika za praćenje (loss, accuracy, f1, auc, balanced_acc)

# Ostalo
use_cuda: true           # Da li koristiti GPU
grad_clip_value: 1.0     # Vrednost za gradient clipping