data:
  csv_file: balansirani_podaci.csv
  data_dir: C:\Users\Marko\MELANOMA\ISIC_2020_Training_JPEG\train
  output_dir: ./models\run_20250428_222622
  valid_size: 0.2
ensemble:
  create_ensemble: true
  method: average
  min_precision: 0.7
  optimize_threshold: true
  target_recall: 0.925
fairness:
  balance_groups: false
  evaluate_by_group: true
kfold:
  n_splits: 5
  random_state: 42
  shuffle: true
  use_kfold: true
model:
  architectures:
  - resnet50
  - efficientnet_b0
  - convnext_tiny
  - mobilenetv3_large
  dropout: 0.5
  img_size: 256
  pretrained: true
training:
  batch_size: 32
  early_stopping_patience: 7
  epochs: 25
  grad_clip_value: 1.0
  learning_rate: 0.0002
  lr_factor: 0.5
  lr_patience: 3
  min_lr: 1.0e-05
  monitor_metric: balanced_acc
  num_workers: 4
  pin_memory: true
  scheduler: cosine
  use_class_weights: true
  use_mixed_precision: true
  weight_decay: 0.0001
